// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package images

import (
    _ "embed"
)

var (

    //go:embed test2.txt
    Test2_txt []byte

)
