// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package images

import _ "embed"


//go:embed test1.md
var Test1_md string

//go:embed test2.txt
var Test2_txt string

//go:embed test3.pdf
var Test3_pdf []byte

