// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package templates

import _ "embed"


//go:embed embed.tmpl
var Embed_tmpl string

