// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package sounds

import _ "embed"


//go:embed sound1.txt
var Sound1_txt string

//go:embed sound2.md
var Sound2_md string

