// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package sounds

import (
    _ "embed"
)

var (

    //go:embed sound1.txt
    Sound1_txt []byte

)
